CREATE TABLE [dbo].[ContentTag]
(
	[ContentTagId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ContentId] INT  NOT NULL,
	[TagId] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[UPdatedAt] DATETIME NOT NULL
)
