CREATE TABLE [dbo].[ContentTag]
(
	[ContentTagID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ContentID] INT  NOT NULL,
	[TagID] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[UPdatedAt] DATETIME NOT NULL
)
