CREATE TABLE [dbo].[MediaAsset]
(
	[MediaAssetID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [MediaCoverID] UNIQUEIDENTIFIER NOT NULL, 
    [FilePath] VARCHAR(250) NOT NULL, 
    [UploadedBy] BIGINT NOT NULL, 
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UpdatedAt] DATETIME NULL
)
