CREATE TABLE [dbo].[Profile]
(
	[ProfileId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserId] INT NOT NULL,
	[Bio] VARCHAR (250),
	[Age] INT,
	[DateOfBirth] DATETIME NOT NULL,
	[CreatedAt] DATETIME NOT NUll DEFAULT GETDATE(), 
    [UpdatedAt] DATETIME NULL
)
